-- CREATE TABLE restaurant (
--       id SERIAL NOT NULL PRIMARY KEY
--     , name VARCHAR NOT NULL
--     , distance NUMERIC CHECK (distance >= 0) 
--     , stars NUMERIC(2, 1) CHECK (stars >= 0)
--     , category VARCHAR NOT NULL
--     , favorite_dish VARCHAR
--     , does_takout BOOLEAN
--     , last_visit DATE
-- );

-- INSERT INTO restaurant VALUES (DEFAULT, 'Toms Chicken', 3.5, 3, 'american', 'Classic Fried Chicken Legs', False, '04/02/2017');
-- INSERT INTO restaurant VALUES (DEFAULT, 'Moon Tower', 10, 5, 'BBQ', 'Moon Pie', True, '04/02/2018');
-- INSERT INTO restaurant VALUES (DEFAULT, 'McDonalds', 2, 2, 'american', 'Quarter Pounder with Cheese', True, '03/30/2018');
-- INSERT INTO restaurant VALUES (DEFAULT, 'Giacommos', 5, 5, 'italian', 'Pucceri Puccini', True, '04/05/2018');
-- INSERT INTO restaurant VALUES (DEFAULT, 'Onion Creek', 3.5, 3, 'american', 'Frito Pie', False, '02/15/2018');
-- INSERT INTO restaurant VALUES (DEFAULT, 'Chipotle', .75, 3, 'mexican', 'Chicken burrito', True, '04/04/2018');